services:
  nginx-certbot:
    image: nginx
    environment:
      - LISTEN_IP4
    ports:
      - ${LISTEN_IP4}:80:80
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./config/nginx-certbot/conf:/etc/nginx/conf.d/default.conf:ro


  certbot:
    image: certbot/certbot
    depends_on:
      - nginx-certbot
    environment:
      - CERTBOT_EMAIL
      - CERTBOT_DOMAIN
    command: certonly --reinstall --webroot --webroot-path=/var/www/certbot --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email -d ${CERTBOT_DOMAIN}
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
